### ISSUE TITLE
Theme possibility

### ISSUE THREAD

**Issue by bedroesb** [elixir-europe/infectious-diseases-toolkit#1]
Instead of the gradient in the headings we could also have this:
![Screenshot from 2021-12-13 11-43-43](https://user-images.githubusercontent.com/44875756/145798381-d5a45873-c0ab-48e1-a279-b2eb7cef24f0.png)

Using

```css
h1:after {
    content: " ";
    display: block;
    height: 4px;
    border-radius: 2px;
    background-image: $color-gradient;
    margin-top: 5px;
  }
```
